<?php

namespace Services\Requests;

class Session extends BaseGlobalsArray
{
    public function __construct(array $session=[])
    {
        $this->array=$session;
    }

    public function setField(string $name, mixed $value = false): void
    {
        parent::setField($name, $value);
        $_SESSION[$name] = $value;
    }
    public function removeField(string $name): void
    {
        parent::removeField($name); // TODO: Change the autogenerated stub
        unset($_SESSION[$name]);
    }
}